data:
    dataset: "tnmg"
    category: "tnmg"
    fs: 400

classifier:
    seq_length: 4096
    lr: 0.001
    patience: 12
    net_filter_size: [64, 128, 196, 256, 320]
    net_seq_lengh: [4096, 1024, 256, 64, 16]
    dropout_rate: 0.8
    kernel_size: 17
    n_leads: 1

diffusion_train:
  feats: 80

diffusion:
  beta_start: 0.0001
  beta_end: 0.5
  num_steps: 50
  schedule: "quad"